#!/usr/bin/env python3
"""Generate a self-hosted activity card for the Axira-A profile README.
Uses only Python's standard library and the GitHub REST API.
On API failure, the existing SVG is preserved.
"""
from __future__ import annotations

import json
import os
import sys
import urllib.request
from datetime import datetime, timezone
from html import escape
from pathlib import Path

USERNAME = "Axira-A"
OUT = Path(__file__).resolve().parents[1] / "assets" / "activity.svg"
API = f"https://api.github.com/users/{USERNAME}/repos?per_page=100&sort=updated&type=owner"


def request_json(url: str):
    token = os.getenv("GITHUB_TOKEN", "")
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "Axira-A-profile-action",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=20) as response:
        return json.load(response)


def trunc(text: str, max_len: int) -> str:
    text = " ".join((text or "").split())
    return text if len(text) <= max_len else text[: max_len - 1].rstrip() + "…"


def main() -> int:
    try:
        repos = request_json(API)
    except Exception as exc:
        print(f"GitHub API unavailable; preserving previous card: {exc}", file=sys.stderr)
        return 0

    repos = [r for r in repos if not r.get("fork") and r.get("name") != USERNAME][:4]
    rows = []
    y = 116
    if not repos:
        rows.append(f'<text x="48" y="{y}" class="muted">No public project repositories yet.</text>')
    else:
        for repo in repos:
            name = escape(trunc(repo.get("name", "Unnamed"), 34))
            desc = escape(trunc(repo.get("description") or "Active project", 70))
            lang = escape(repo.get("language") or "—")
            stars = int(repo.get("stargazers_count") or 0)
            updated = (repo.get("updated_at") or "")[:10]
            rows.append(f'<text x="48" y="{y}" class="repo">{name}</text>')
            rows.append(f'<text x="330" y="{y}" class="desc">{desc}</text>')
            rows.append(f'<text x="952" y="{y}" class="meta">{lang} · ★ {stars} · {updated}</text>')
            y += 42

    rows_svg = "".join(rows)
    svg = f'''<svg width="1000" height="300" viewBox="0 0 1000 300" xmlns="http://www.w3.org/2000/svg">
<rect width="1000" height="300" rx="18" fill="#0d1117"/>
<rect x="1" y="1" width="998" height="298" rx="17" fill="none" stroke="#3b352d"/>
<style>
.title {{ font: 700 22px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#d8d2c5; }}
.kicker {{ font: 12px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#776e61; letter-spacing:1px; }}
.repo {{ font: 700 14px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#c4a46f; }}
.desc {{ font: 12px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#aaa295; }}
.meta {{ font: 11px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#6f685e; text-anchor:end; }}
.muted {{ font: 13px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#8b8377; }}
</style>
<text x="48" y="54" class="title">LATEST PUBLIC WORK</text>
<text x="48" y="82" class="kicker">SELF-HOSTED · GENERATED BY GITHUB ACTIONS</text>
{rows_svg}
<text x="952" y="272" class="meta">activity through {escape((repos[0].get("updated_at") or "")[:10] if repos else "—")}</text>
</svg>'''
    OUT.write_text(svg, encoding="utf-8")
    print(f"Updated {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
