#!/usr/bin/env python3
"""Generate the self-hosted activity card used by Axira-A's profile README.

Design goals:
- standard-library only;
- GitHub REST API only;
- preserve the previous SVG if the API is unavailable;
- ignore forks, empty repositories and the profile repository itself;
- stable output so scheduled runs do not create meaningless commits.
"""
from __future__ import annotations

import json
import os
import sys
import urllib.request
from collections import Counter
from html import escape
from pathlib import Path

USERNAME = "Axira-A"
OUT = Path(__file__).resolve().parents[1] / "assets" / "activity.svg"
API = f"https://api.github.com/users/{USERNAME}/repos?per_page=100&sort=pushed&type=owner"


def request_json(url: str):
    token = os.getenv("GITHUB_TOKEN", "")
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "Axira-A-profile-action",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=20) as response:
        return json.load(response)


def trunc(text: str, max_len: int) -> str:
    text = " ".join((text or "").split())
    return text if len(text) <= max_len else text[: max_len - 1].rstrip() + "…"


def main() -> int:
    try:
        all_repos = request_json(API)
    except Exception as exc:
        print(f"GitHub API unavailable; preserving previous card: {exc}", file=sys.stderr)
        return 0

    public = [
        r
        for r in all_repos
        if not r.get("private")
        and not r.get("fork")
        and r.get("name") != USERNAME
        and int(r.get("size") or 0) > 0
        and not r.get("archived")
    ]
    public.sort(key=lambda r: r.get("pushed_at") or "", reverse=True)
    repos = public[:4]

    total_stars = sum(int(r.get("stargazers_count") or 0) for r in public)
    languages = Counter(r.get("language") for r in public if r.get("language"))
    primary_language = languages.most_common(1)[0][0] if languages else "—"
    last_push = (repos[0].get("pushed_at") or "")[:10] if repos else "—"

    rows: list[str] = []
    y = 159
    if not repos:
        rows.append(f'<text x="56" y="{y}" class="muted">No public project activity yet.</text>')
    else:
        for repo in repos:
            name = escape(trunc(repo.get("name", "Unnamed"), 32))
            desc = escape(trunc(repo.get("description") or "Active project", 62))
            lang = escape(repo.get("language") or "—")
            pushed = (repo.get("pushed_at") or "")[:10]
            rows.append(f'<circle cx="61" cy="{y-5}" r="3" fill="#c59b59"/>')
            rows.append(f'<text x="78" y="{y}" class="repo">{name}</text>')
            rows.append(f'<text x="340" y="{y}" class="desc">{desc}</text>')
            rows.append(f'<text x="944" y="{y}" class="meta">{lang}  ·  {escape(pushed)}</text>')
            y += 40

    rows_svg = "".join(rows)
    svg = f'''<svg width="1000" height="340" viewBox="0 0 1000 340" xmlns="http://www.w3.org/2000/svg">
<defs>
  <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="#0b1016"/>
    <stop offset="1" stop-color="#111820"/>
  </linearGradient>
</defs>
<rect width="1000" height="340" rx="18" fill="url(#bg)"/>
<rect x="1" y="1" width="998" height="338" rx="17" fill="none" stroke="#4d402e"/>
<path d="M56 95 H944" stroke="#6f5836" stroke-width="1"/>
<path d="M487 95 L500 82 L513 95 L500 108 Z" fill="#c59b59" opacity=".9"/>
<style>
.title {{ font: 700 22px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#e3dccd; letter-spacing:2px; }}
.kicker {{ font: 11px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#887a66; letter-spacing:1.5px; }}
.metric {{ font: 700 12px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#c59b59; }}
.repo {{ font: 700 13px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#dfd4c0; }}
.desc {{ font: 12px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#a9a091; }}
.meta {{ font: 11px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#7f7669; text-anchor:end; }}
.muted {{ font: 13px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; fill:#8b8377; }}
</style>
<text x="56" y="48" class="title">LATEST PUBLIC WORK</text>
<text x="56" y="72" class="kicker">SELF-HOSTED  ·  GENERATED BY GITHUB ACTIONS</text>
<text x="944" y="48" class="meta">last push  {escape(last_push)}</text>
<text x="944" y="72" class="metric" text-anchor="end">{len(public)} REPOS  ·  {total_stars} STARS  ·  {escape(primary_language)}</text>
{rows_svg}
<text x="944" y="318" class="meta">github.com/{USERNAME}</text>
</svg>'''
    OUT.write_text(svg, encoding="utf-8")
    print(f"Updated {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
